#!/usr/bin/env python3
"""R4 (C-48, meta prompt §12.3): the volatility register, built from the time-sensitive claims the six parts already mark.

Usage:  volatility.py ROOT          → ROOT/volatility-register.md (deterministic; no timestamps of its own)

A claim is a course line (code excluded) that carries one of the parts' own markers:
  `(verify…)`                 not checked against a live source in this refactor → status "to verify"
  `Verified YYYY-MM-DD …`     a blockquote note that checks the claim on the line above it → status "checked"
  `as of <date>`              a dated statement → status "dated"
  `(checked on 1.27.1)`       Go behaviour run on that release (the Go part's §13 says when) → status "checked"
                              ("partly checked" when the same line also carries a `(verify)`)
The category is a keyword heuristic over the claim (exam date / domain weight / product name / GA status / price /
quota / release behaviour / other); read it as a sorting aid, not as a judgement. No claim is re-verified here.
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from verify import COURSE, SHORT, code_mask   # noqa: E402

NAMES = dict(zip(COURSE, ["main course", "System Design Primer companion", "SQL companion", "Design Patterns companion",
                          "Cloud Cybersecurity companion", "Go companion",
                          "Forward Deployed Engineer companion"]))
VER = re.compile(r"^> \*\*Verified (\d{4}-\d{2}-\d{2})([^:]*):\*\*")
MARK = re.compile(r"\(verify|\(checked on 1\.27\.1\)|\bas of (?:\d{4}-\d{2}-\d{2}|(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|"
                  r"Oct|Nov|Dec)[a-z]* \d{1,2},? \d{4})", re.I)
CATS = [("exam date", r"(?i)\bexam\b.*\b(date|day|retire|beta|window|launch|last)|\blast exam day|\bretire|\bbeta\b"),
        ("domain weight", r"(?i)\bweights?\b|\d+(\.\d+)?\s*/\s*\d+(\.\d+)?\s*/|\bsections?\b.*\d+%|domain"),
        ("price", r"(?i)\$\s?\d|\bprice|\bpricing|\bcost[s]? \$|free tier|always-free|per (hour|month|GB)"),
        ("quota", r"(?i)\bquota|\blimit(s|ed)? (of|to|is)|\bmax(imum)? \d"),
        ("GA status", r"(?i)\bGA\b|\bpreview\b|general availability|deprecat|sunset|\bbeta\b"),
        ("product name", r"(?i)\brenam|\bbranding|\bnow called|\bformerly|\bname\b"),
        ("release behaviour", r"(?i)\(checked on 1\.27\.1\)|\bGo 1\.\d+|\brelease\b|\bversion\b")]


def cat(s):
    return next((c for c, rx in CATS if re.search(rx, s)), "other")


def clip(s, n=180):
    s = re.sub(r"\s+", " ", s).strip().replace("|", "\\|")
    return s if len(s) <= n else s[:n - 1] + "…"


def main():
    root = os.path.abspath(next((a for a in sys.argv[1:] if not a.startswith("--")), "."))
    rows = []
    for f in COURSE:
        L = open(os.path.join(root, "work", f), encoding="utf-8").read().split("\n")
        mk = code_mask(L)
        seen = set()
        for i, l in enumerate(L):
            if mk[i]:
                continue
            v = VER.match(l)
            if v:
                j = i - 1
                # the note checks the claim above it; under a cert's checkbox and Lab Reality lines, that is the cert line
                while j >= 0 and (not L[j].strip() or L[j].startswith(("- **Lab Reality**", "- [ ]"))):
                    j -= 1
                seen.add(j)
                rows.append((f, j + 1, clip(L[j]) + " — " + clip(l.split(":**", 1)[1], 160), cat(L[j] + " " + l),
                             v.group(1), "vendor's live page" + v.group(2).replace(" against the vendor's live page", ""),
                             "checked"))
        for i, l in enumerate(L):
            if mk[i] or i in seen or VER.match(l) or not MARK.search(l):
                continue
            if "(checked on 1.27.1)" in l:
                d, src, st = "2026-09-24", "run on Go 1.27.1 (the Go part's §13)", "checked"
                if re.search(r"\(verify", l):
                    st = "partly checked"   # one claim on the line was run, another is marked (verify)
            elif re.search(r"(?i)\bas of \d{4}-\d{2}-\d{2}", l):
                d, src, st = re.search(r"(?i)\bas of (\d{4}-\d{2}-\d{2})", l).group(1), "the line's own date", "dated"
            elif re.search(r"(?i)\bas of [A-Z][a-z]+ \d", l):
                d, src, st = re.search(r"(?i)\bas of ([A-Z][a-z]+ \d{1,2},? \d{4})", l).group(1), "the line's own date", "dated"
            else:
                d, src, st = "not checked", "none recorded", "to verify"
            rows.append((f, i + 1, clip(l), cat(l), d, src, st))
    rows.sort(key=lambda r: (COURSE.index(r[0]), r[1]))
    by = {}
    for r in rows:
        by.setdefault((NAMES[r[0]], r[6]), 0)
        by[(NAMES[r[0]], r[6])] += 1
    md = ["# Volatility register", "",
          "Generated by `refactor-tools/volatility.py` (re-run: `python3 refactor-tools/volatility.py .`) from the markers "
          "the six parts already carry: `(verify…)`, `Verified <date>` notes, `as of <date>` and the Go part's "
          "`(checked on 1.27.1)`. Nothing was re-verified to build it. Line numbers are in `work/`.", "",
          "Rules (§12.3): a claim older than 90 days at teaching time is re-verified, or read out with its date. Four to "
          "six weeks before an exam, every row for that cert is re-checked, as the main course's Part IX requires. A "
          "`to verify` row is taught as unverified until it is checked.", "",
          "The category column is a keyword heuristic, for sorting only.", "",
          "## Counts", "", "| Part | checked | partly checked | dated | to verify |", "|---|---|---|---|---|"]
    for f in COURSE:
        n = NAMES[f]
        md.append(f"| {n} | {by.get((n, 'checked'), 0)} | {by.get((n, 'partly checked'), 0)} | {by.get((n, 'dated'), 0)} "
                  f"| {by.get((n, 'to verify'), 0)} |")
    md += ["", f"Total rows: {len(rows)}.", "", "## Register", "",
           "| # | Claim | Part:line | Category | Last checked | Source | Status |", "|---|---|---|---|---|---|---|"]
    for k, (f, ln, c, ca, d, src, st) in enumerate(rows, 1):
        md.append(f"| {k} | {c} | {SHORT[f]}:{ln} | {ca} | {d} | {src} | {st} |")
    open(os.path.join(root, "volatility-register.md"), "w", encoding="utf-8").write("\n".join(md) + "\n")
    print(f"volatility: {len(rows)} rows; " + ", ".join(f"{a} {b} {v}" for (a, b), v in sorted(by.items())))


if __name__ == "__main__":
    main()
