import subprocess, json, os, sys
ENV = dict(os.environ, PGHOST="localhost", PGPORT="54329", PGUSER="lab", PGDATABASE="labdb")
def sql(x, tup=False):
    p=subprocess.run(["psql","-X","-At","-q","-v","ON_ERROR_STOP=1"],input=x,capture_output=True,text=True,env=ENV)
    if p.returncode: print("ERR",p.stderr[:300]); 
    return p.stdout.strip()
def plan(q, pre=""):
    out=sql(pre+"\nEXPLAIN (ANALYZE, BUFFERS OFF, TIMING OFF, SUMMARY OFF, FORMAT JSON) "+q+";")
    j=json.loads(out[out.index("["):])
    res=[]
    def walk(n,d=0):
        res.append("  "*d+f"{n['Node Type']}"+(f" on {n['Relation Name']}" if 'Relation Name' in n else "")+(f" using {n['Index Name']}" if 'Index Name' in n else "")+f"  est={n['Plan Rows']} act={n.get('Actual Rows')}" + (f" sortmethod={n['Sort Method']}" if 'Sort Method' in n else "")+ (f" heapfetches={n['Heap Fetches']}" if 'Heap Fetches' in n else ""))
        for c in n.get('Plans',[]): walk(c,d+1)
    walk(j[0]['Plan']); return "\n".join(res)
def show(t,q,pre=""):
    print("\n### "+t); print(q.strip()); print(plan(q,pre))
sql("""DROP TABLE IF EXISTS work.o; CREATE TABLE work.o AS SELECT * FROM lab.customer_order; ALTER TABLE work.o ADD PRIMARY KEY (order_id); ANALYZE work.o;
DROP TABLE IF EXISTS work.u; CREATE TABLE work.u AS SELECT * FROM lab.app_user; ALTER TABLE work.u ADD PRIMARY KEY (user_id); ANALYZE work.u;""")
show("P1 before index","SELECT * FROM work.o WHERE user_id = 42")
sql("CREATE INDEX o_user_placed ON work.o (user_id, placed_at DESC); ANALYZE work.o;")
show("P1 after index","SELECT * FROM work.o WHERE user_id = 42")
show("P1 user 1 (hot key)","SELECT * FROM work.o WHERE user_id = 1")
show("P1 user 1900 (never ordered)","SELECT * FROM work.o WHERE user_id = 1900")
show("P1 latest 5 for user 42","SELECT * FROM work.o WHERE user_id = 42 ORDER BY placed_at DESC LIMIT 5")
show("P2 sargability: function on column","SELECT count(*) FROM work.o WHERE placed_at::date = '2025-03-01'")
sql("CREATE INDEX o_placed ON work.o (placed_at); ANALYZE work.o;")
show("P2 same, index exists","SELECT count(*) FROM work.o WHERE placed_at::date = '2025-03-01'")
show("P2 rewritten as range","SELECT count(*) FROM work.o WHERE placed_at >= '2025-03-01' AND placed_at < '2025-03-02'")
show("P3 leading wildcard","SELECT * FROM work.u WHERE email LIKE '%@t1.example.com'")
sql("CREATE INDEX u_email ON work.u (email); ANALYZE work.u;")
show("P3 prefix LIKE with default btree","SELECT * FROM work.u WHERE email LIKE 'user1%'")
sql("CREATE INDEX u_email_pat ON work.u (email text_pattern_ops); ANALYZE work.u;")
show("P3 prefix LIKE with text_pattern_ops","SELECT * FROM work.u WHERE email LIKE 'user1%'")
sql("CREATE INDEX o_ts ON work.o (tenant_id, status, placed_at); ANALYZE work.o;")
show("P4 leftmost eq+eq+range","SELECT * FROM work.o WHERE tenant_id = 2 AND status = 'paid' AND placed_at >= '2025-03-01' AND placed_at < '2025-03-08'")
show("P4 skip leading column","SELECT * FROM work.o WHERE status = 'paid' AND placed_at >= '2025-03-01' AND placed_at < '2025-03-08'")
show("P4 OR of two indexed cols","SELECT * FROM work.o WHERE user_id = 42 OR order_id = 7")
sql("DROP INDEX work.o_ts; CREATE INDEX o_cov ON work.o (tenant_id, placed_at) INCLUDE (total_minor); VACUUM ANALYZE work.o;")
show("P5 covering / index-only","SELECT sum(total_minor) FROM work.o WHERE tenant_id = 2 AND placed_at >= '2025-03-01' AND placed_at < '2025-04-01'")
sql("CREATE INDEX o_created ON work.o (order_id) WHERE status = 'created'; ANALYZE work.o;")
show("P6 partial index hit","SELECT order_id FROM work.o WHERE status = 'created' AND order_id > 15000")
show("P7 join large","SELECT count(*) FROM lab.order_line l JOIN lab.product p USING (product_id)")
show("P7 join small side filtered","SELECT * FROM lab.order_line l JOIN lab.product p USING (product_id) WHERE p.product_id = 42")
sql("DROP TABLE IF EXISTS work.p; CREATE TABLE work.p AS SELECT * FROM lab.product; ANALYZE work.p;")
show("P8 correlated columns (before)","SELECT * FROM work.p WHERE tenant_id = 4 AND currency = 'EUR'")
sql("CREATE STATISTICS p_dep (dependencies) ON tenant_id, currency FROM work.p; ANALYZE work.p;")
show("P8 correlated columns (after CREATE STATISTICS)","SELECT * FROM work.p WHERE tenant_id = 4 AND currency = 'EUR'")
show("P9 OFFSET deep","SELECT * FROM work.o ORDER BY order_id OFFSET 19000 LIMIT 20")
show("P9 keyset","SELECT * FROM work.o WHERE order_id > 19000 ORDER BY order_id LIMIT 20")
show("P10 sort default work_mem","SELECT * FROM lab.event ORDER BY occurred_at")
show("P10 sort with 64kB work_mem","SELECT * FROM lab.event ORDER BY occurred_at","SET work_mem='64kB';")
show("P11 hash agg","SELECT user_id, count(*) FROM lab.event GROUP BY user_id")
show("P11 hash agg 64kB","SELECT user_id, count(*) FROM lab.event GROUP BY user_id","SET work_mem='64kB';")
sql("DROP TABLE work.o, work.u, work.p")
